name: Pin Bar Signals

on:
  schedule:
    - cron: '0 * * * *'      # هر ساعت یکبار چک کنه
  workflow_dispatch:

jobs:
  signals:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: pip install requests
      
      - name: Run Pin Bar Signals
        env:
          EMAIL: ${{ secrets.EMAIL }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
        run: python pinbar_signals.py
